### ISSUE TITLE
DEBUG: Cannot render an array variable as a string

### ISSUE THREAD

**Issue by labSupport** [dryven/cookie-byte#10]
Hey there,

maybe this is not an issue but we noticed debug log entries associated with the Cooky Byte addon if the `{{ cookie_modal }}` tag is placed in the antlers layout. The exact message may vary but generally says the same:
`local.DEBUG: Cannot render an array variable as a string: {{ code:code }}`
or `production.DEBUG: Cannot render an array variable as a string: {{ abstract }}`
or `production.DEBUG: Cannot render an array variable as a string: {{ code }}`

Tested in different environments
- PHP >= 8.1
- Laravel 9.x

**Comment by Ceepster14** [comment]
Same here - we include the {{ cookie_modal }} tag in our base layout and it generates a huge number of the following in the log which bloats it enormously:

[2023-02-08 18:01:15] local.DEBUG: Cannot render an array variable as a string: {{ code }}

**Comment by dryven-dano** [comment]
Hey @labSupport and @Ceepster14!

Thanks for filing the issue. Could you tell me which versions of Statamic and CookieByte you use by running `php artisan statamic:support:details`? Does resaving the cookie byte settings in the control panel and running `php artisan vendor:publish --tag=cookie-byte-views --force` get rid of the log entries? (Keep in mind this will restore any changes in the view to CookieByte's defaults)

Cheers,
Dano.

**Comment by labSupport** [comment]
Hey @dryven-dano,

thanks for your reply.
I am using Statamic `Version: 3.3.65 PRO` and `ddm-studio/cookie-byte: 1.0.17`
Updating to the latest versions of Statamic and Cookie Byte I seem to get rid of the issue.
