### ISSUE TITLE
Reload page after saving

### ISSUE THREAD

**Issue by wm-simon** [dryven/cookie-byte#18]
Hey, thanks for your addon. Is it possible to reload the page, after saving the cookie settings?

**Comment by dryven-daniel** [comment]
Hey @wm-simon,
do you mean to reload the Cookie-Byte settings page, or to reload the website where it's displayed?

**Comment by wm-simon** [comment]
Hey @dryven-daniel ,

I mean to reload the current website after saving. I use a lot something like
```
{{ if { cookie_consent has="marketing-cookies" } }}
    {{# code that should be executed #}}
{{ /if }}
```
and it would be nice, when the user gives the permission to load the right content.

**Comment by dryven-daniel** [comment]
Hey @wm-simon, 
I think what you are looking for is a cookie-cover, it perfectly fits your needs. Check it out in the documentation: https://statamic.com/addons/dryven/cookie-byte/docs#antlers-tags 😄 

Another option would be to add a code snippet to the respective cookie categories inside the control panel: `window.location.reload()`

**Comment by wm-simon** [comment]
hey @dryven-daniel ,

I know the covers. Problem is, I have a multisite and use the site attributes, for example the jtag from google analytics.

That's why it's not working for me. This is my code:
```
    {{ if { cookie_consent has="stats" } }}
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-3HNNB52HF8"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', '{{ site:attributes:gtag }}', { 'anonymize_ip': true });
    </script>
    {{ /if }}
```
I think this `{{ site:attributes:gtag }}` is not working with covers, right? I get error massages, when I add the script as snippets.
