### ISSUE TITLE
Listen for consent change without publishing assets

### ISSUE THREAD

**Issue by wiegertschouten** [dryven/cookie-byte#26]
Hi guys,

Thanks for the great addon. Implemented it on several sites, works great so far.

I have now run into an issue where I have a slider containing links to several videos. Consent is needed, so I wrapped the slider in a `cookie_cover`. Which works great, except for the fact that the slider, which is initialized using JavaScript, does not work when the user clicks the 'Accept' button in the cookie cover, because the JS only runs once on page load, and not after the user accepts the necessary cookies.

I would like to be able to initialize the slider *after* the user has clicked that 'Accept' button.

In order to do that, I would like to attach a callback using `window.CookieConsent.registerCallback`. But I can't, because Cookie Byte's script is deferred, so I get a race condition when I try to access the `CookieConsent` object.

I could probably solve this problem by publishing the addon's assets, but I don't want to do that. I do not want to customize anything else, and I don't want to maintain these files because I'm lazy (which I think is a virtue for a developer 😉).

But I think there is an easy solution to this: emitting a custom event when the addon's JS has finished loading. An example of this is the Consent API as implemented by Cloudflare Zaraz: https://developers.cloudflare.com/zaraz/consent-management/api/. They emit a `zarazConsentAPIReady` event as soon as the API is ready for use. 

If Cookie Byte could emit such an event, it would enable me to listen for that, and call my code after consent has been given by the user. It could look like this:

```js
window.addEventListener('cookieByteReady', () => {
    window.CookieConsent.registerCallback('marketing', () => {
        // My code does its thing
    });
});
```
This would make it a lot easier to implement custom behavior based on consent changes.

Does this make sense? If so, would it be possible to implement this? If it helps, I would be happy to try and submit a PR.

**Comment by dryven** [comment]
Thanks for your suggestion and your offer to contribute. It sounds like a great enhancement. We'd definitely appreciate a PR for this functionality. Looking forward to your contribution!

**Comment by dryven** [comment]
Thanks for your help with #27 !
Merged

**Comment by wiegertschouten** [comment]
👍🏻 Glad I could help!
