### ISSUE TITLE
Show the privacy conditions page without the consent model

### ISSUE THREAD

**Issue by Sennik** [dryven/cookie-byte#28]
I like this add-on!

I also like the blurred cover when consent was not given yet. But some of my visitors also like to read the privacy conditions BEFORE they give consent. Is it possible to exclude endpoint from the cookie-byte model?

**Comment by dryven-daniel** [comment]
Hi @Sennik,
thanks for your suggestion! Currently, this is not possible. But we will definitely think about implementing it.
