### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by websmyth** [dryven/cookie-byte#29]
When I add a `<script>` or `<noscript>` element inside a **Code snippets** block, Cookie Byte doesn’t load and there’s a console error on the frontend. This happens even if I choose `HTML` as the Code Snippet type. I’m guessing this is being interpreted as JS.

If I remove the `<script>` or `<noscript>` elements, Cookie Byte loads as normal.

---
Environment
Laravel Version: 10.42.0
PHP Version: 8.2.10
Composer Version: 2.3.5
Environment: staging
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: sendmail
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.46.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
ddm-studio/cookie-byte: 1.4.3
edalzell/forma: 2.1
spatie/statamic-responsive-images: 4.1.1
statamic-rad-pack/mailchimp: 4.1.1
withcandour/aardvark-seo: 3.0.0

**Comment by dryven-daniel** [comment]
Dear @websmyth,

thank you for this issue. Currently only plain javascript code is supported, but we are working on a solution where script tags can be included as well.

We will keep you updated.

**Comment by websmyth** [comment]
Thanks for getting back to me. I’ll close this for now as I didn’t use the add-on in the end.
